image: "smblott/dcu-docker-gitlab-ci"

testA1:
  script:
    - "django-admin --version"
    - "echo ok checking submission for A1"
    - "echo checking for restaurant.csv and campus.csv"
    - "ls data/restaurant.csv"
    - "ls data/campus.csv"
    - "echo found restaurant.csv and campus.csv"
    - "echo checking for load_db_data.py"
    - "ls src/load_db_data.py"
    - "echo found load_db_data.py"
    - "cd src; python3 manage.py test eatatdcu"
    - "echo running python django test"
    - "echo finished A1 submission checks"
